disabled_rules: # rule identifiers to exclude from running
  - line_length
  - function_body_length
  - unused_closure_parameter
  - valid_docs
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - SwiftyJSONAcceleratorTests
  - Pods
  - Core/External-Libraries
  - SwiftyJSONAccelerator/External-Libraries
  - SJAccelerator/External-Libraries
  - SwiftyJSON
  - SwiftCLI
