disabled_rules:
- trailing_whitespace
- line_length
- compiler_protocol_init
- force_try
opt_in_rules:
- empty_count
- empty_string
excluded:
- Pods
- SwiftyJSONAccelerator/UI/External-Libraries
function_body_length:
    warning: 300
    error: 500
function_parameter_count:
    warning: 6
    error: 8
type_body_length:
    warning: 300
    error: 500
file_length:
    warning: 1000
    error: 1500
    ignore_comment_only_lines: true
cyclomatic_complexity:
    warning: 15
    error: 25
reporter: "xcode"
